import type { Metadata } from "next";
import { Poppins } from "next/font/google"; // ✅ Add this
import "./globals.css";

// ✅ Set up the Poppins font
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins", // for use in Tailwind
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={poppins.variable}> {/* ✅ Attach variable */}
      <body>{children}</body>
    </html>
  );
}
